[tool.poetry]
name = "asyncoptoma"
version = "0.1.0"
description = ""
authors = ["Sebastian Lübke <luebke@gonicus.de>"]

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.27.0"
bs4 = "^0.0.2"

[tool.poetry.dev-dependencies]
autoflake = "^2.0.0"
isort = "^5.10.1"
black = "^24.0.0"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
